### PR TITLE
Implementation for jintrac v220922

### LINKED ISSUE #484: Make duqtools compatible with local imasdb's (Jintrac v220922)
I'm getting a bunch of failed jetto runs, because duqtools create no longer writes the run number to the `jintrac_imas_config.cfg` file. Defaults to the next number in sequence (1, 2, 3 etc). This causes my runs to fail.

- I checked that `jetto.jset` has the correct run numbers.
- Also seems to be happening with older runs that ran successfully previously.

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR implements `v220922` with the local imas db. I have added a new system (`JettoSystemV210921` and `JettoSystemV220922`). The difference is a method that defines the data locations for the create step and jetto (`data_in` / `data_out`).

Seems to work for `duqtools create` and `duqduq create`.

Closes #484

### Todo

- [ ] Documentation (especially the `data: ...` block in the `duqtools.yaml`.
- [x] Update tests for local imas db
- [x] Make sure jetto actually runs without error -> #488
- [x] `duqduq setup` also does some tracking of the run numbers to avoid clashes. This can be made more clear that it is an implementation detail for `v210921` and not required for `v220922`. Alternatively, we can make the large scale validation only work with `v220922` onwards.
- [ ] Test duqduq setup changes on gateway

### CODE REVIEW

**Comment by stefsmeets** [comment]
@v1kko Can you have a look and let me know what you think?

**Review by v1kko — COMMENTED** [review]
I like it, especially that with the new 220922 system the imasdb is assumed to be in the directory, which makes it a lot simpler. I think this is the right way to implement it.

We could also allow relative paths (also assume user is a path if starting with a `.`) , but since Jintrac does do that, maybe we shouldn't either

**Comment by stefsmeets** [comment]
Cheers, I will finish up this PR then!

**Comment by stefsmeets** [comment]
Duqtools part works well, just that jetto is not working yet, I'm going to merge this so we can try to fix it with #480

**Pull request merged**
