### PR TITLE
Add hdf5 capabilities

### PR DESCRIPTION
**Pull request by v1kko**

### CODE REVIEW

**Comment by stefsmeets** [comment]
I'm working on code to write back to hdf5 atm, could we link this to `imas2xarray`?

**Comment by v1kko** [comment]
That would solve the problem of IMAS just segfaulting when trying to open a HDF5 entry. So I am in favor of doing this via imas2xarray instead

**Comment by stefsmeets** [comment]
The plan:
- ImasHandle -> MDSPlusHandle (keep access through access layer), becomes legacy
- New HD5Handle, goes to imas2xarray for loading the data
- New way of operating on xarray (necessary to refactor on _apply_model)
- ImasPath (user,machine,shot,run), direct path (pathlib.Path)

**Comment by stefsmeets** [comment]
@v1kko Do you want to have a check before we merge this?

**Comment by stefsmeets** [comment]
I'm closing this in favour of #706

**Pull request closed without merging**
